// <auto-generated />
namespace VlogRoom.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Updatedminmaxstringlengthsofvideoproperties : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updatedminmaxstringlengthsofvideoproperties));
        
        string IMigrationMetadata.Id
        {
            get { return "201710160346401_Updated min-max string lengths of video properties"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
